title = 'Auguang Maitreya'
baseURL = 'https://main--cheerful-churros-efd63e.netlify.app/'
languageCode = 'en-au'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
Paginate = 3

[module]
[[module.imports]]
path = 'github.com/theNewDynamic/gohugo-theme-ananke'

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
cover_dimming_class = "bg-black-30"
recent_posts_number = 3

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/auguangmaitreya"
[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/Auguangmaitreya/"

[build.processing]
skip_processing = true
